version: "3"
services:
  api: # FIXME: 壊れてると思う(Dockerfile内で起動コマンドを打つようにしたため)
    build:
      context: ./back
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: kyo
      POSTGRES_PASSWORD: password
    volumes:
      - ./back/storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
