# https://qiita.com/ysk91_engineer/items/904a5bc881eda8a10df8
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: gomamayo-db
  username: kyo
  password: <%= ENV['DB_PASSWORD'] %> # .envで設定
