FROM ruby:3.3

RUN apt-get update && apt-get install -y \
    mecab \
    libmecab-dev \
    mecab-ipadic-utf8 \
    git \
    sudo

RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git /usr/local/src/mecab-ipadic-neologd && \
    cd /usr/local/src/mecab-ipadic-neologd && \
    ./bin/install-mecab-ipadic-neologd -n -y && \
    echo "dicdir = `mecab-config --dicdir`/mecab-ipadic-neologd" > /usr/local/etc/mecabrc

WORKDIR /app

COPY back/Gemfile* .
RUN bundle install

COPY back .

CMD ["bash"]
