name: back
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  rubocop:
    name: Rubocop Check and Rails Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - working-directory: back
        run: |
          bundle install
          rubocop
          rails test
