name: back
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  rubocop:
    name: Rubocop Check and Rails Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Create image tag
        id: image_tag
        run: |
          # Define cache dir
          CACHE_PATH="/tmp/docker_cache"
          # Get Dockerfile hash for image cache
          IMAGE_HASH="${{ hashFiles('docker/Dockerfile.test', 'back/Gemfile.lock') }}"
          # Create image tag
          IMAGE_NAME="gomamayo-share"
          TAG="${IMAGE_NAME}:${IMAGE_HASH}"
          # Cache dir setting
          TAR_NAME="${IMAGE_NAME}_${IMAGE_HASH}.tar"
          TAR_PATH="${CACHE_PATH}/${TAR_NAME}"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "TAR_PATH=${TAR_PATH}" >> $GITHUB_OUTPUT
          echo "CACHE_PATH=${CACHE_PATH}" >> $GITHUB_OUTPUT
          echo "CACHE_KEY=${IMAGE_NAME}_${IMAGE_HASH}" >> $GITHUB_OUTPUT

      - name: Enable cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.image_tag.outputs.CACHE_PATH }}
          key: ${{ steps.image_tag.outputs.CACHE_KEY }}

      - name: Load image from cache if exists
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          docker load -i ${{ steps.image_tag.outputs.TAR_PATH }}

      - name: Build Docker image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker build -t ${{ steps.image_tag.outputs.TAG }} -f docker/Dockerfile.test .
          mkdir -p ${{ steps.image_tag.outputs.CACHE_PATH }}
          docker save ${{ steps.image_tag.outputs.TAG }} > ${{ steps.image_tag.outputs.TAR_PATH }}

      - name: Rubocop
        run: docker run -v /back:/app --rm ${{ steps.image_tag.outputs.TAG }} rubocop

      - name: Rails Test
        run: docker run -v /back:/app --rm ${{ steps.image_tag.outputs.TAG }} rails test
