name: back
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  rubocop:
    name: Rubocop Check and Rails Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Build Docker image
        run: docker build -t gomamayo-share-back-test -f docker/Dockerfile.test .

      - name: Rubocop
        run: docker run --rm gomamayo-share-back-test rubocop

      - name: Rails Test
        run: docker run --rm gomamayo-share-back-test rails test
