name: format
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - working-directory: front
        run: |
          npm install
          npm run lint

  rubocop:
    name: Rubocop Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - working-directory: back
        run: |
          bundle install
          rubocop
