name: front
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - working-directory: front
        run: |
          npm install
          npm run lint
