name: Cloudflare Pages Storybook
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  publish:
    name: Publish Storybook
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Storybook
        working-directory: front
        run: |
          npm install
          npm run build-storybook
    
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: cloudflare-pages-gomamayo-share-storybook
          directory: front/storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
